### ISSUE TITLE
How to get the count?

### ISSUE THREAD

**Issue by eNepper** [janhommes/o.js#102]
I'm trying to work with o.js in an Angular App and rand into a problem. I can't figure out how to only get the count returned.

Here is a sample of what I have tried:
this.odata = o(apiUrl, config);
this.odata.get('Buildings').query({$count: true, $top: 0});

**Comment by janhommes** [comment]
If you only want to get the count you need to add it to the resource, as everything in the query parameter only gets attached to the [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams):

`this.odata.get('Buildings/$count').query()`
