### ISSUE TITLE
How can I take count from response?

### ISSUE THREAD

**Issue by anton-marchenko** [janhommes/o.js#105]
When I make a request like `GET serviceRoot/User?$count=true`
I receive a list of users.

```
    odata(O_DATA_URL)
      .get('User')
      .query({ $count: true })
      .then(data => console.log(data)) // [ {...}, {...} ]
```

How can I get count that consists in my response:

```
{
    "@odata.context": ".../$metadata#...",
    "@odata.count": 15, // I do not see this in my "console.log(data)"
    "value": [
        {...}
     ]
}
```

**Comment by janhommes** [comment]
This is sadly a tradeoff that comes with the data parsing. There is no other way than using the `fetch` call as mentioned in the README.md:

 > The lib tries to parse the data on each request. Sometimes that is not wanted (e.g. when you need a status-code or need to access odata metadata), therefore you can use the .fetch method that acts like the default fetch.
