### ISSUE TITLE
No way to specify relative URL's for batch elements.

### ISSUE THREAD

**Issue by melgish** [janhommes/o.js#108]
When batch is created it's creating fully qualified URL's for batch items.  I'd like to add configuration setting to batchConfig along with appropriate code to use relative URL's. 

Behavior would default to false to maintain compatability.

Opening the topic here to discuss.

**Comment by janhommes** [comment]
I am fine with it. As I haven't worked that much with `$batch` endpoints, I am not sure what the spec says. When looking over the spec I can only the absolutes pathes:
http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31360930

**Comment by melgish** [comment]
There's a bit more in the section on batch requests.

https://docs.oasis-open.org/odata/odata/v4.01/cos01/part1-protocol/odata-v4.01-cos01-part1-protocol.html#sec_MultipartBatchRequestBody

I'm thinking I can implement the "example 100" version cheaply using:
batchUrl = encode(request.url.href.replace(root.url.href, ''));

A better approach would be to capture the original resource value, but that would require modifying more than OBatch.ts and runs a greater risk of not being backward compatible.

**Comment by janhommes** [comment]
yeah, let's use the cheap variant and simply remove it. And make it opt-in in the config.

**Comment by janhommes** [comment]
@melgish do you plan to work on this soon? As I want to release a 1.1.0 version with your changes and a dependency update.

**Comment by melgish** [comment]
Sure I can take care of it today.
