### ISSUE TITLE
Any oauth examples

### ISSUE THREAD

**Issue by nafwa03** [janhommes/o.js#112]
I just found this package and am liking it a lot. I read on one of the issues mentioning one of the oauth examples. Where can I find that?

**Comment by janhommes** [comment]
Glad that you like it. Not sure which issue you mean, but in general this lib has nothing todo with OAuth. OAuth is mostly handled via cookies (or headers). You can set headers in the options, but most properly you don't need to, as when http-only cookies are used, they are attached to each request automatically. 

Sorry, if you have some more concrete questions, I might be able to help you.
