### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by anibarro** [janhommes/o.js#113]
Hello,

The library is not working in IE11, https://janhommes.github.io/o.js/example/ fails with a "require is not defined" here:
<pre>const env = typeof window !== "undefined" ? window : global;
if (!("fetch" in env) && !config.disablePolyfill) {
   require("cross-fetch/polyfill");
}</pre>

Is the incompatibility intended? Thanks!

**Comment by janhommes** [comment]
looks like a bug to me:
https://unpkg.com/odata@1.1.0/dist/umd/o.js

require calls should not be there. I guess we need to resolve the polyfills and inline them. The question is only if then the `disablePolyfill` setting makes any sense.

**Comment by anibarro** [comment]
> looks like a bug to me:
> https://unpkg.com/odata@1.1.0/dist/umd/o.js
> 
> require calls should not be there. I guess we need to resolve the polyfills and inline them. The question is only if then the `disablePolyfill` setting makes any sense.

Thanks for looking into this :)
In this case disabling them won't save any space... Including the polyfills is a nice touch, but I would personally let the user handle the polyfills if needed

**Comment by janhommes** [comment]
your suggestion is to don't inline any polyfills at all?

Mh, yeah might be a solution. The idea was basically (if I remember correctly) that the umd module is used by older browsers, which includes them by default. In the es2015 model (which is used by modern browsers) they are loaded only if needed. Wouldn't that make sense?

**Comment by anibarro** [comment]
From what I can see in "caniuse.com", browsers compatible with ES6 also supports fetch and url, so it looks like polyfills won't be needed in the es2015.
I'm not sure what's the best solution, I couldn't make it work in IE11 even after transpiling the code with babel, I have to check that as well

**Comment by janhommes** [comment]
true, that's why there is the check for `fetch` and `url` to not load the polyfill if supported. Idea was that the umd module is slightly bigger, while esm can transpile it on their own and can decide if they want to use it. But I guess that is not gonna work that way :/

**Comment by janhommes** [comment]
As discussed, the polyfills should now be excluded and the require call should not happen anymore.
