### ISSUE TITLE
.fetch doesn't return headers

### ISSUE THREAD

**Issue by jeffersoneagley** [janhommes/o.js#117]
I'm doing this:
```
    const oQueryResponseList = await odata(
      url
      getDefaultRequestConfig()
    )
      .get(endpoint)
      .fetch(someQuery);
    const myHeader = response.headers.get('x-some-header');
```

When I do this, I don't get any headers back, just `null`. Is this supposed to be not supported?

**Comment by janhommes** [comment]
Basically, it's the [fetch response](https://developer.mozilla.org/en-US/docs/Web/API/Response). So yes this should be supported. Your sure this header is set by your server? Also what happens if you ask for some default header like `content-type`?
