### ISSUE TITLE
Can make count to work

### ISSUE THREAD

**Issue by pintobikez** [janhommes/o.js#118]
Using the example provided I could not retrieve the count of a resource.

```
const total = await this.odata()
			.get('Contacts/$count')
			.query()
			.then((count) => {});
```

total is undefined
I've done console.log of the count and I still cant get the result

**Comment by janhommes** [comment]
Can you check your network tab? In the example the count call is working:
https://janhommes.github.io/o.js/example/#People

Code used there:
https://github.com/janhommes/o.js/blob/334e0782d81cb259917954048206d260c77e35f8/example/browser.js#L51

Btw, I guess you are mixing Promise and await/async. it should be either:
```
const total = await this.odata()
			.get('Contacts/$count')
			.query();
```

or:
```
this.odata().get('Contacts/$count').query().then((count) => console.log(count));
```

**Comment by pintobikez** [comment]
Oh my god you're totally right.... Sorry about it
