### ISSUE TITLE
Bundle size pretty big, since universal-url

### ISSUE THREAD

**Issue by 243083df** [janhommes/o.js#126]
Seems like url-polyfill must be used instead.

**Comment by janhommes** [comment]
mh, can you point me which file you mean? The polyfill itself?

the main file is quite alright, or not? https://unpkg.com/browse/odata@1.3.1/dist/umd/

**Comment by 243083df** [comment]
File size is ok, but probles is that this is not all code, since it contains `require("universal-url")` and another requires.
And when webpack try to build bundle, it connect every require with package including universal-url with tr46

**Comment by janhommes** [comment]
I see. Didn't think of webpack.

I guess I need to place everything inside `o.polyfill.ts`.

**Comment by janhommes** [comment]
The require calls are there to make it work in node.js if fetch or URL is not present. As said, did not think about webpack.

Just checked out this:
https://stackoverflow.com/questions/34828722/how-can-i-make-webpack-skip-a-require

Maybe it is worth a try to use `window.require`?

**Comment by janhommes** [comment]
could you try this one if the require() calls are still picked up by webpack?
https://www.npmjs.com/package/o.js/v/1.4.0-rc0

**Comment by 243083df** [comment]
Still picked up :C
