### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by darklajid** [janhommes/o.js#13]
Stumbled upon this library - and it looks awesome.

If you create a release (see #11 ) - would it be possible to submit this to npm?
I can wrap it in a package myself, but it'd be awesome if you'd add the required bits (a suitable package.json, mostly?) for npm to be happy. Would you accept a PR for that?

**Comment by janhommes** [comment]
Do you want to use this lib in node? Or do you just want to use npm as a package manager for browser applications? First will not work, caused of the different handling of ajax calls. 2nd is planed but will take some time. Any PR is welcome if you want to contribute.

**Comment by darklajid** [comment]
The latter. I'd use this library in the browser, but use webpack and npm to manage the build/dependencies etc. I'll see if I can help with the package.

**Comment by janhommes** [comment]
npm package is registered with the new version. 

`npm install o.js`
