### ISSUE TITLE
can't get @odata.count data from response

### ISSUE THREAD

**Issue by BobbleHatkjh** [janhommes/o.js#133]
ihave wrote a GET request example such like demo in readme
but i can't get the total count number which already shown in chome's NETWORK tab, i only could get the value data.
how could i do to resolve this problem

<img width="653" alt="Screen Shot 2022-04-14 at 5 16 32 PM" src="https://user-images.githubusercontent.com/35591106/163354639-9cf072e0-c6e3-4753-bdc7-1ea472b7a3fc.png">
<img width="653" alt="Screen Shot 2022-04-14 at 5 17 53 PM" src="https://user-images.githubusercontent.com/35591106/163354651-d2bbdf35-eed5-4aba-8040-33aa926e76c3.png">
<img width="654" alt="Screen Shot 2022-04-14 at 5 18 15 PM" src="https://user-images.githubusercontent.com/35591106/163354660-60ea099e-85e7-41ea-8026-7bb07164b529.png">

**Comment by janhommes** [comment]
Sorry for the late response.

See: https://github.com/janhommes/o.js#just-fetching
query() tries to be smart by parsing the result leading to that you only get the data. You can use `fetch()` instead to get all.
