### ISSUE TITLE
request should return a promise but instead returns void

### ISSUE THREAD

**Issue by sksallaj82** [janhommes/o.js#152]
I did an npm install yesterday, and there seems to be an error here:

Following the JS docs
 
     const req = new ORequest('http://full.url/health', ( method : 'HEAD' });
     var a = await o('http://another.url').request(req).fetch()
     
 I fetch() doesn't work because request() returns void. I prefer if it returns a promise so I can use .then().catch()
 
 In fact, it'd probably be better if I could just do
 
    const h = o(myConfig)  // where OdataConfig is passed, having everything defined
    h.request('/check').query({ ... })
    
the reason for having the request be this generic is because the passed in myConfig would already have the method (ie get, post, etc) defined.

Better yet, It'd be ideal if OdataConfig has a property called 'queryPath' so that when passed in, I could just do

    h.query({ ... })   // throws an error if I do this and querypath is not defined, and request isn't even needed

**Comment by janhommes** [comment]
true, we should add `return this;` to https://github.com/janhommes/o.js/blob/master/src/OHandler.ts#L202

I am open to a PR here. Otherwise, I will fix it in the next iteration (basically when I have time to look into this again).
