### ISSUE TITLE
Can't we get the URL-building functionality only?

### ISSUE THREAD

**Issue by webJose** [janhommes/o.js#156]
Hello!  Thanks for your work on this.  I am interested because I'm searching for a package that can create an OData query string since I really don't want to read the RFC and program it myself.  Your package looks promising, but the fact that is bundled with the fetching and parsing functions that I don't need is a deal-breaker.

May I suggest that you create a less opinionated package that only builds the query string?

Thanks!

**Comment by janhommes** [comment]
Hi,

thanks for your suggestion. I plan to work on a 2.0.0 release wich is less opinionated and includes https://www.npmjs.com/package/odata-query

But I guess for you odata-query is exactly what you are searching for, so I suggest to use this.

Regards
jan

**Comment by webJose** [comment]
Ah, I see.  Thanks!
