### ISSUE TITLE
If-Match header on non-CORS requests

### ISSUE THREAD

**Issue by IceOnFire** [janhommes/o.js#16]
Hi Jan,

First of all thank you for this amazing library, I was just looking for a clean way to perform OData operations and yours is just what I needed: simple, elegant, intuitive.

However I had to adapt it to my needs,and would like to share some suggestions in the following issues.

First of all, the "If-Match" header: I had to remove it otherwise it triggers CORS on calls to http://services.odata.org/V4/Northwind/Northwind.svc/. Is it necessary for other purposes? I would make it totally optional.

Keep up the good work!

Antony

**Comment by janhommes** [comment]
Hi,

thanks. I added it for the testing (it is needed for the TripPinService) and thought there would be no side effect. Did not know that it will trigger CORS requests. So I am going to make it optional.

Regards
Jan

**Comment by IceOnFire** [comment]
Sorry Jan,

I removed the header myself and updated all tests so they include it where necessary. Hope I'm not conflicting with your work...

Antony

**Comment by janhommes** [comment]
Fixed in v0.2.1. Merged #21
