### ISSUE TITLE
ie8 xhr patch method not support

### ISSUE THREAD

**Issue by lenoray** [janhommes/o.js#25]
Hi @janhommes 

We use o.js in our intranet, all the pc are xp with ie8. And we found a problem,  ie8 XMLHttpRequest not support patch method. Maybe, it should check the browser, if it is ie8, xhr should be activexhttprequest instead of xmlhttprequest.

Thanks

function createCORSRequest(method, url) { 
1446             var xhr = null; 
1447 
 
1448             //if no window assume node.js 
1449             if (typeof window === 'undefined') { 
1450                 var Xhr2 = require('xhr2'); 
1451                 xhr = new Xhr2(); 
1452             } 
1453             else { 
1454                 xhr = new XMLHttpRequest(); 
1455             }

**Comment by janhommes** [comment]
Hi,

sorry I need to test more in IE8 but do not have enough time. Can you please check if we can just switch to the ActiveX as follow?

```
 //if no window assume node.js
            if (typeof window === 'undefined') {
                var Xhr2 = require('xhr2');
                xhr = new Xhr2();
            }
            else if(typeof window.XMLHttpRequest !== 'undefined') {
                xhr = new XMLHttpRequest();
            }
            else {
                //IE 8 support
                xhr = new ActiveXObject('MSXML2.XMLHTTP.3.0');
            }
```

Thanks,
Jan

**Comment by lenoray** [comment]
thanks, I will test it today.

**Comment by janhommes** [comment]
@lenoray any update on this? Does it work?

**Comment by janhommes** [comment]
No feedback from @lenoray.
