### ISSUE TITLE
Support advanced queries

### ISSUE THREAD

**Issue by techniq** [janhommes/o.js#26]
Currently I'm using `ODataAngularResources` which has support for some very [advanced queries](https://github.com/devnixs/ODataAngularResources#advanced-queries).  Any thoughts about bringing this type of api/functionality over to `o.js`?

Also, their [transformUrl](https://github.com/devnixs/ODataAngularResources#transform-the-final-query-url) function is very handy as well to add support for anything missing, such as aggregates.  For exaxmple, I have the following which produces a group by count summary based on some filtered columns

``` js
odataQuery.transformUrl(url => url + `&$apply=groupby((${columns.join(',')}),aggregate(Id with countdistinct as Total))`);
```

**Comment by janhommes** [comment]
Hey, 

It was planed to add a expression parser to map Javascript to odata queries. E.g. `.filter("LastName == 'x' && Title != 'Mr'")` get parsed to `$filter=((LastName eq 'x') and (Title ne 'Mr'))`. But maybe the idea of having predicates is also a good idea.

I could imagine something like this `o('http://some/').filter('LastName', '==', 'x').filter('Title', '!=', 'y')`;  

The transform URL method we can add in the next release. That is actual a good idea.

Regards
Jan

**Comment by janhommes** [comment]
#83 -> no operations mapping anymore. Filter must be real odata-filters.
