### ISSUE TITLE
Not utilizing "http_proxy" and "https_proxy" standard environment variables

### ISSUE THREAD

**Issue by dewdad** [janhommes/o.js#32]
I could not get this library to work from behind a proxy.

**Comment by janhommes** [comment]
I am not sure what you mean. In my understanding this lib has nothing to do with a proxy. Is there anything in the odata v4 specs?

**Comment by dewdad** [comment]
It has nothing to do with oData but rather HTTP requests. Most modern node
modules respect the environment variables enabling working through proxies.
People in institutions, be they corporate or educational usually route
through proxies.

**Comment by janhommes** [comment]
yep, I know what a proxy is. I was just confussed where you need a proxy, because on just client-side you never need it. But you are using o.js on the backend in node.js, am I right? That might be an issue with the used xhr (ajax) simulator module. We need to look into it, if they support proxies.

**Comment by dewdad** [comment]
Right sorry, I  forgot to mention I was using your library with Node. I
don't believe the XHR module supports proxy configuration through the
environment variables.

**Comment by janhommes** [comment]
All I found about is this issue: https://github.com/pwnall/node-xhr2/issues/1
As I can say they fixed it by adding a `nodejsSetAgents()` function, but I am not sure, how we need to implement this into o.js.
