### ISSUE TITLE
Adding a timeout

### ISSUE THREAD

**Issue by Unforgiven-wanda** [janhommes/o.js#38]
Hello,
I would like to add a timeout of 2 seconds to all my requests (using NodeJS). I tried modifying the `o.js` file at line 1450 like this: 

```javascript
var Xhr2 = require('xhr2');
xhr = new Xhr2();
xhr.timeout = 2000;
```

to no avail. Is there some way I can remedy this issue?
Thank you.

**Comment by janhommes** [comment]
Hi,

xhr2 is an external lib we implemented for node.js support. Normaly your approach should work. If not, it might be an issue with the xhr2 lib [implementation](https://github.com/pwnall/node-xhr2/blob/d2d39294abad0adf4db745ded691310b540d3ef0/src/001-xml_http_request.coffee). Please open an issue there.

Not quite sure but maybe you can try:
```
xhr = new Xhr2({ timeout: 2000 });
```

Regards
Jan

**Comment by Unforgiven-wanda** [comment]
Thank you for the fast answer. I believe you are right, it is working now.
Good day.
