### ISSUE TITLE
How to auth NTLM 

### ISSUE THREAD

**Issue by faludigabor** [janhommes/o.js#40]
Hey,  

I have an OData Endopoint that I need to auth against w/ NTLM. Dont seem to  work. 
Any ideas? 
Tx,Gabor

**Comment by janhommes** [comment]
Hi,
o.js only supports basic auth. If you want to use NTLM you need to set the correct header yourself. To do so you can add a header in the `oConfig`:

```
headers: [],		//an array of additional headers [{name:'headername',value:'headervalue'}]
```
