### ISSUE TITLE
expand multiple levels

### ISSUE THREAD

**Issue by datoulei** [janhommes/o.js#42]
How to build like this:  `Products/?$expand=ProductUnit($expand=ProductPrice)`

**Comment by janhommes** [comment]
As I wrote this lib there was no multi expand support. If your endpoint supports it, o.js can query it in the following way:
```
o('http://localhost/Products/?$expand=ProductUnit($expand=ProductPrice)').get()
```

Not tested, but should work!

**Comment by janhommes** [comment]
No feedback if it's work. Assuming so -> closed.
