### ISSUE TITLE
Q.JS dependency 

### ISSUE THREAD

**Issue by a2life** [janhommes/o.js#49]
Hi
could you double check if q.js dependency was fixed in V-0.3.1?  I am still seeing the 'defer' undefined error once I remove Q.js link from my markup.

I am also seeing unless I configure  "content-type:  application/json" in the header,  SharePoint REST service returns xml payload instead of json, so the code bombs out at the first character of JSON.parse(response) .  I am not sure if this is a particular issue with Microsoft SharePoint service.

**Comment by janhommes** [comment]
Hi,

can you check [this commit](https://github.com/janhommes/o.js/commit/a2cb27fdde664d1da5ba0883f12a742e5af59f4d) for the Q dependency if its then working?

For the second point: o.js assuming that your service returning JSON by default or was using the v3 property `$format=json`. Maybe we can set it as default value for all v4 services. Are you sure it is safe to set this header by default?

Regards
Jan

**Comment by a2life** [comment]
Hi
No dice.
o.js:455 Uncaught TypeError: Cannot read property 'defer' of null

Also for the second point,  I mentioned "content-type' but it is actually 'Accept' header that I need to set up. If you look at MS site page that explains SharePoint service page here, https://msdn.microsoft.com/en-us/library/office/dn531433.aspx

> Accept header : Specifies the format for response data from the server. The default format is  application/atom+xml. Example:

**Comment by janhommes** [comment]
Okay, [here another try](https://github.com/janhommes/o.js/commit/046fb3d9e7937082ab57dc8a2eae023848f36789). Can you pls test this version (sorry, I have no real test service any more)?

I think we could safely set the accept header to JSON. I will implement this enhancement as soon as we fix the promise bug.

**Comment by a2life** [comment]
Thank you, it is finally working.
