### ISSUE TITLE
Make multiple expands possible

### ISSUE THREAD

**Issue by heinzchr** [janhommes/o.js#5]
o("Product").expand(["Address","MainIMage_fk"]).get()

**Comment by heinzchr** [comment]
Sorry, this works with the following syntax:
o("Product").expand("Address, MainIMage_fk").get()
But the syntax should be the same as in the route concatenation...

**Comment by janhommes** [comment]
You can aslo use `o('Product').expand('ProductUnit').expand('ProductImage')`
