### ISSUE TITLE
.count does not prepend with /

### ISSUE THREAD

**Issue by yleflour** [janhommes/o.js#51]
I tried using this library but when doing the following:

```
o().config(myConfig);
o('appointments').count().get();
```

I get a *404* because the url is *<myEndpoint>/products$count* instead of *<myEndpoint>/products/$count*.

And the following works:

```
o().config(myConfig);
o('appointments/').count().get();
```

I am new with OData so I am not sure I am using the library well.

If this is not a bug, can you correct me with how to use the `.count()` method?

**Comment by janhommes** [comment]
I think [this](https://github.com/janhommes/o.js/commit/18b819d57d14586d28ac3a231a25803799181c5a) commit broke that. I commited a fix into master, can you check that?

**Comment by lusid** [comment]
We are having this same issue, but are currently just including the / at the end when we do a .count(). Any idea when this will get pushed to npm? And will our code continue to work without issues even with the extra / or will it break until we've fixed our code to remove them?

**Comment by janhommes** [comment]
@lusid your right, that will lead to double slashes in cases where someone has fixed it this way. Someone has to look deeper into this.

**Comment by zhevron** [comment]
This seems to affect everything that uses `.appending`, including `$ref`.

The quick'n'dirty fix would just be to let it generate double slashes and let people remove their workarounds in their own time, Or would you rather detect double slashes between URL segments and correct them?

I'm looking into a few problems using o.js against my API and might as well take a stab at this one. Just need to know which way you want to go with this. :)

**Comment by janhommes** [comment]
Actual I got another idea to fix this. Sadly I have no real odata service to test this and tests are not in place. Can you check the commit 941c431?

Basically we adding it to the resource list instead of adding it to a query. As the resource list is a parsed array, the path is correctly joined together. 

BTW: When you have good (and tested) fixes from your API test with o.js, feal free to make a PR.

**Comment by zhevron** [comment]
Pulled the new commit and it seems promising so far. The request URLs look fine in the traffic dumps and the API responds to them. However, it does seem to append a trailing `/` to every URL now, which makes it look rather funky in the browser dev tools.

![image](https://user-images.githubusercontent.com/2384772/31812288-c76e5184-b582-11e7-9caa-d9e24d6a28a4.png)

And I fully intend to submit PRs for any problems/missing features I encounter. So far, I'm very pleased with the ease of use. Much better than hacking together requests using Axios as I was before. ;)

**Comment by janhommes** [comment]
Okay. So I hoped that it will not add a trailing slash, because some odata services cannot handle them. I need to look deeper into that to get the trailing slash away.

**Comment by janhommes** [comment]
closed https://github.com/janhommes/o.js/tree/v0.3.7

**Comment by be236** [comment]
So I did "npm install odata" in the last few days, and when using $count, I still dont see the / prepended to the end of the URL, so it still fails.

Debug shows this URI " ... something_uri/resource$count failed with HTTP status 404"

**Comment by zhevron** [comment]
@be236 Could you make sure you're using the latest version and post the query that causes this output? As far as I can tell from digging into the code, the issue should not occur with the latest release.

**Comment by be236** [comment]
Yes, I am using latest o.js file, as shown here in its first line (I used:  $ npm install odata a few days ago):
// +++
// o.js  v0.3.7

And it has new "raw" data structure in it (o.js) as well.. so this is latest.

Now my o() call is this:
        o(`${MYURL1}`).count().get((result) => {

Where MYURL1 is "https://<my_server_ip>/mgmt/odata/tm/ltm/pool"

When I make that count() call above, I get this error back from o.js:

  Uncaught Request to https://<my_server_ip>/mgmt/odata/tm/ltm/pool?$count=count failed with HTTP status 404.
  Error

See it is translating the URI to "... pool?$count" instead of the correct way of " .. pool/$count."

**Comment by be236** [comment]
Also, can you give me example of using $ref in a GET context? Specs says this:

To request entity references in place of the actual entities, the client issues a GET request with /$ref
appended to the resource path.

**Comment by zhevron** [comment]
@be236 Is this an OData v4 API? `?$count=count` seems to be how it handles counting in a v3 API.

And as far as I can tell, `.ref` does not support GET requests. You should, however, be able to request it directly within the query.

Something like this:
```js
o('Products(1)/Category/$ref').get(result => { })
```

Could you point me to the part of the spec you quoted?

**Comment by be236** [comment]
Yes, my server is OData v4.0 only service.

So, for $count, if I use this for its URL: https://<my_server_ip>/mgmt/odata/tm/ltm/pool/$count
I will get my count of how many pool objects in my system, and it would return a number, like 4 or 10, or whatever I had.

As for $ref usage/syntax, it's in this PDF: http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html

Search for "$ref" in there, or go to section 10.11 or 11.2.7, as shown here for using $ref with GET:

11.2.7 Requesting Entity References
To request entity references in place of the actual entities, the client issues a GET request with /$ref appended to the resource path.
If the resource path does not identify an entity or a collection of entities, the service returns 404 Not Found.

**Comment by zhevron** [comment]
Extracted from the most recent source file:
https://github.com/janhommes/o.js/blob/cae947ace3d0fc3dafd3a190846cebf564a56916/o.js#L332-L341

The `?$count=count` syntax _should_ only be applied for v3 APIs, but you seem to be getting it on v4. I'll see if I can reproduce the issue locally.

As for the $ref thing, I've opened a new feature request for you in #63. Feel free to comment on it there.

**Comment by zhevron** [comment]
I just implemented a call to `.count()` in my production frontend and I'm unable to reproduce the case above.

I'm calling the API like this:
```js
o('Customers').count().get(result => console.log(result));
```

Which triggered an HTTP request to:
```
http://localhost:8080/api/odata/Customers/$count?$format=json
```

And the expected count response was printed to my console.

So it would seem something is causing o.js to treat your API as a v3 API. Could you try outputting the version o.js is configured with right before your query is sent?
```js
var query = o('https://<my_server_ip>/mgmt/odata/tm/ltm/pool').count();
console.log('OData version: ' + query.oConfig.version);
query.get(result => console.log('$count result: ' + result));
```

You can also try forcing v4 using the `.config()` method (although 4 *is* the default value):
```js
o().config({ version: 4 });
```

**Comment by be236** [comment]
I must have inadvertently set my config() setting to version 2.

After setting it to version 4, $count works correctly for me now.

Thanks for looking into this.
