### ISSUE TITLE
Need to update "npm install odata" with fix from this repo

### ISSUE THREAD

**Issue by be236** [janhommes/o.js#52]
Hi,

You made a fix for $count, to make it "/$count."

So, you may need to do this fix for $ref too, since it needs to be: /$ref at the end of URL, per OData v4 specs.

And yes, still need to get your fixes into "npm install odata," since your last fix is only in this Git Repo.

And can you update your this README page of the supported query commands vs what is listed inside the top of the o.js lib file?

**Comment by zhevron** [comment]
See #51 for why it hasn't been pushed to npm yet. I need it updated as well in order to push to staging/production.

Also, the commit fixes `$ref` URLs as well, so no worries there. :)
