### ISSUE TITLE
Cookies are not send even is CORS is enabled

### ISSUE THREAD

**Issue by jcchalte** [janhommes/o.js#54]
When a CORS request is made, currently, no cookies are sent to the odata server, even if isCors is enabled.

There seems to be a missing line of code right before opening the XHR, the withCredential XHR field is not set, but it is mandatory to do CORS requests (at least into Chrome). I have made a simple pull request ( #53 ) to correct this but there are evidences in the code that the withCredential field has been taken into account (at least partially), so I don't know if I am not missing something by just setting it to true.

**Comment by janhommes** [comment]
PR accepted. Thanks for contributing.
