### ISSUE TITLE
o().conf({version: 2}) not working?

### ISSUE THREAD

**Issue by be236** [janhommes/o.js#55]
Hi,

So I have OData service that supports version "4.0" string exactly, and if I use OData-Version header directly in o.js config or using curl, it works as I would expect.

But if I set this o() config to the above and use any value, like 2, or 5, etc... my OData service seems to ignore that value and continues to return all my data. I expected my service to reject me with an error, like "version 2 not supported."

Is this version field working correctly?

**Comment by janhommes** [comment]
We don't have any version headers in place currently. The version setting is just to let o.js know how to handle some request. 

If you like you can submit a PR with strict header setting.

**Comment by be236** [comment]
Can we turn this Issue into PR, then?

**Comment by janhommes** [comment]
Feel free to submit a PR (Pull Request). I personally have no time to do it. You can fork this repository, align it to your needs and submit a PR so everyone can use it.
