### ISSUE TITLE
isCors not included in Readme and in @types/o.js

### ISSUE THREAD

**Issue by jcchalte** [janhommes/o.js#58]
Hi,

I just wanted to submit a small issue. The Readme file and typescript declaration files are not up to date with the latest released version. At least "isCors" option is not documented, which can be important for some projects (it was a prerequisite in my case). I am making 2 pull requests atm for each modification.

**Comment by janhommes** [comment]
Thanks Merged. Did you do a PR to the typing project? If so, can you also have a look at the latest comments for #12 ?

**Comment by janhommes** [comment]
closed https://github.com/janhommes/o.js/tree/v0.3.7
