### ISSUE TITLE
Return response HTTP headers back to O object?

### ISSUE THREAD

**Issue by be236** [janhommes/o.js#62]
When making O() call, can you return the response HTTP headers as well, so I can parse that?

This is feature request for o.js lib.

**Comment by janhommes** [comment]
We can use the `XMLHttpRequest` object and attach them to the callback result.

**Comment by DerGuteWolf** [comment]
I second this, please add the headers eg to oHandler.
Use case for me is with SAP OData v4 implementation additional infos are returned in various headers.

**Comment by janhommes** [comment]
Can you see that PR #73 if it fits your needs?

**Comment by DerGuteWolf** [comment]
From looking at the source code this looks good, however I am currently busy with other stuff, so it will take some time until I can test it.
