### ISSUE TITLE
Using results in react-native List

### ISSUE THREAD

**Issue by mikevbaker** [janhommes/o.js#75]
I realize this probably isn't because of o.js but I can't figure it out and I'm running out of people/places to ask. I'm trying to render the results from an odata call into a list.

```    return (
      <ScrollView>
        <List>
          {
            this.state.products.map((item, i) => {
              console.log(item.ItemCode); // THIS PART WORKS!!!
              <ListItem key={item.ProductId}
                title={"Item " + item.ItemCode}
              />
            })
          }
        </List>
      </ScrollView>
    )
```

What's drive me nuts is that the items are there. They're listed in the console. But the items don't appear in the list. What gives?
TIA, Mike

**Comment by janhommes** [comment]
That has really nothing to do with o.js. Because I am a nice guy I try to help:

I guess you need to return the ListItems (never worked with react ;) ):
```
    <ScrollView>
        <List>
          {
            this.state.products.map((item, i) => {
             return (<ListItem key={item.ProductId}
                title={"Item " + item.ItemCode}
              />)
            })
          }
        </List>
      </ScrollView>
```
Or don't use braces `{}`:
```
          this.state.products.map((item, i) => (
              <ListItem key={item.ProductId}
                title={"Item " + item.ItemCode}
              />
            ))

**Comment by mikevbaker** [comment]
FANTASTIC. I knew it wasn't o.js, just some confused syntax on my part
