### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by BruceJillis** [janhommes/o.js#76]
I'm trying to do the following odata call: 
https://<..>/odata/1.0/data.svc/Endpoint?$format=json&$filter=title eq 'Tëst' 
but the call is failing. If I do the corresponding call in the browser it does work however. Is it possible to use unicode with o.js?

**Comment by janhommes** [comment]
Can you be somehow more specific? Which call from o.js is failing?

I added a unit test [in this branch](https://github.com/janhommes/o.js/blob/bug/%2376/spec/o.spec.js#L160), and all test are passing. It tests against the odata reference endpoint and that is data the test creates: https://services.odata.org/V4/(S(ms4wufavzmwsg3fjo3eqdgak))/TripPinServiceRW/People?$filter=UserName%20eq%20%27T%C3%ABst_0.4396934628605862%27&$format=json

All test are passing, so it seems to be okay. Or am I missing smth?

Thanks
jan

**Comment by BruceJillis** [comment]
Smallest example I could make (without the credentials obv):

const path = require("path");
const os = require("os");
const o = require('odata');

function createApplication(applicationName) {
    o().config({
        endpoint: 'https://devportalu34f5b50f-p2000082306trial.hanatrial.ondemand.com/odata/1.0/data.svc/',
        username: '',
        password: ''
    });
    return o('APIMgmt.Applications')
        .filter(`title eq '${applicationName}'`).get()
        .then(function (ans) {
            if (ans.data.d.results.length > 0)
                throw new Error(`${applicationName} already exists!`)
            console.log(ans.data);
    }, function(msg) {
            winston.error(msg);
    })
}
createApplication('Tést')

This returns:
error: Request to https://devportalu34f5b50f-p2000082306trial.hanatrial.ondemand.com/odata/1.0/data.svc/APIMgmt.Applications?$format=json&$filter=title eq 'Tést' failed with HTTP status 400. {"name":"o.js exception","status":400}

but if I do the request in the browser it goes through:
https://i.imgur.com/Sf6HHYi.png

**Comment by janhommes** [comment]
And all other calls work? Only the one containing unicode is failing?
I am sorry, but the tests against the reference implementation are working fine. I cannot say what is going wrong here. It seems like the backend is refusing the request (the error handling of o.js is not the best and needs to be improved, maybe the 400 status is misleading here).

Can you maybe inspect the network traffic with some node.js debugger? E.g. this one: https://github.com/node-inspector/node-inspector
