### ISSUE TITLE
How to configure an instance instead of global configuration

### ISSUE THREAD

**Issue by needo2** [janhommes/o.js#79]
I tried `let q = odata(url, config);`, `let q = odata(config);`, `let q = odata(url); q.config(config);`
None of them worked

**Comment by janhommes** [comment]
yep, the config is always set on `window.oConfig()` and cannot be constructed atm. The design is a bit outdated. There was a PR #34 which intended to change that but it was never finished. Maybe you can try that and see if we can enhance from there?

**Comment by janhommes** [comment]
#83 allows that as it returns an instances `const ohandler = o('http://my.endpoint')`
