### ISSUE TITLE
post() overrides data sent by previously one,  multiple use of post() calle send/save object only in latter one

### ISSUE THREAD

**Issue by kivi** [janhommes/o.js#81]
According to the following example in README, you should be able to do the following and expected behavior is, two records are send the the endpoint.

```javascript 
o(serviceURL).post({Name:'Example 1',Description:'a'}).post({Name:'Example 2',Description:'b'}).save()
```
But what happens is, that last call of post is overriding the data to be send by save()

Furthermore in the README it says 

> .post(object) - Post data to an endpoint

Which is not true, the post function adds the data to the object to `resource.data` and it overrides. Only if you give a second parameter, it ads it to the second parameter. But I don't understand the intention here, that second parameter if given is not used inside that o.js again.

**Comment by janhommes** [comment]
yes, that seems like an issue.
Actual I thought of a total rewrite of that lib, it makes not much sense to maintain such old code and there are now completely different use cases and tools that you can use.

**Comment by kivi** [comment]
What would you recommend to use now instead? The Typescript version? 
I could contribute a bit, if you would like to start from scratch

**Comment by janhommes** [comment]
I would simply use [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) for it.

But I'm curious, maybe you could give me some insights on what you want to use that lib for? Atm I consider to do the following:
 - allow simple configuration of an oHandler that you can pass around in your app to not always set your endpoint again.
 - still allow changing `o('http://my.url').get('my-resource')`
 - parse data directly but still allow to get the full response
 - query parameters `?` simplified by just a typing it
 - batching multiple requests simplified with data parsing
 - everything written in typescript
 - await-able

What I plan to remove:
 - all convenient methods like `find` or `search`, that is something you can simply create on your own today by using template strings (e.g. for find: 
```javascript
o('http://my.endpoint').get(`People($id)`)
```
 - routing (that should not be the task of that lib)

**Comment by kivi** [comment]
We could discuss the features in a new issue. And leave the bug here open.

**Comment by janhommes** [comment]
pls see #83
