### ISSUE TITLE
Patch does not support singleton models

### ISSUE THREAD

**Issue by kartikjain12** [janhommes/o.js#82]
In order to use patch, o.js requires you to have "(id)" in the path. This works most of the time but if you want to patch a singleton model and don't provide "(id)" in the path then the o data client throws an exception "Bulk updates are not supported. You need to query a unique resource with find() to patch/put it."
For example in my javascript code the following does not work
```
var path = `${Base}${endPoint}`
o(path).patch(entity).save(function() {
        resolve()
      }
```
but this will
```
var path = `${Base}${endPoint}(${entity.Id})`
o(path).patch(entity).save(function() {
        resolve()
      }
```

**Comment by janhommes** [comment]
yes, that is an issue. I am currently working on a rewrite of o.js. The code is very old and doesn't find today's needs. Therefore I will not fix that but I will inform you as soon as the new version is available.

**Comment by kartikjain12** [comment]
Thanks for the update @janhommes

**Comment by janhommes** [comment]
https://github.com/janhommes/o.js/tree/feature/version-1.0.0-rc.1

Here is the new version build in typescript. I will create a new npm package and an announcment out of it later that day.

**Comment by janhommes** [comment]
#83
