### ISSUE TITLE
patch usage

### ISSUE THREAD

**Issue by Billskate** [janhommes/o.js#9]
I use patch/put like the document mentioned:
```javascript
o('http://services.odata.org/V4/OData/OData.svc/Products(1)').patch({Name:'NewName'}).save(function(data) {
    console.log("Product Name changed"); 
});
```

but a exception throw:
**Bulk updates are not supported. You need to query a unique resource with find() to patch/put it.**

so, how can I use it correct?

thx

**Comment by janhommes** [comment]
I can't rebuild your error. You are using it correctly. Does the `get` function work? The tests are working correctly.

Do you use integer or sting as id?

**Comment by Billskate** [comment]
yes, the get function work.
I build it on jsfiddle:
https://jsfiddle.net/billskate/0Ltbvwwz/1/
I just copy and paste the patch's sample code, the same exception occured.

**Comment by janhommes** [comment]
Thanks. This is a bug if you patch something without a endpoint configured. I sos updated the repo directly. Please try again with the new release.

One note: The Product-Service of odata.org seems to be read only. To test this, please use the TripPinService: http://services.odata.org/V4/%28S%28wptr35qf3bz4kb5oatn432ul%29%29/TripPinServiceRW/
