### ISSUE TITLE
Request failed, reason: unable to get local issuer certificate - Proxy?

### ISSUE THREAD

**Issue by pmc-sstaehle** [janhommes/o.js#93]
Hi there,

I want to use this library within a (server-side) nestJS project. I managed to include it into my application but when I try to get the resource, it gives me the following error message:
`'request to https://AddressInCompanyNetwork/resource.xsodata/XYHeader?%24format=json failed, reason: unable to get local issuer certificate'`.

I'm within a company internal network. Maybe I have to set a security proxy? Do you guys have any ideas?

**Comment by janhommes** [comment]
sounds like the certificate is missing. Do you have the possibility to use http instead?

**Comment by pmc-sstaehle** [comment]
Unfortunately no :-(

**Comment by janhommes** [comment]
You can disable node checking for certificates: https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

**Comment by pmc-sstaehle** [comment]
ok, thx. I will try that.
