### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by GhostMayor** [janhommes/o.js#96]
where can I get detailed documentation on methods  ?

**Comment by kevinchiu** [comment]
Also looking for documentation. Specifically the syntax for deleting relations (links) between entities.

**Comment by janhommes** [comment]
so for that you best look at the odata spec:
http://docs.oasis-open.org/odata/odata/v4.01/csprd05/part2-url-conventions/odata-v4.01-csprd05-part2-url-conventions.html#sec_AddressingReferencesbetweenEntities

Basically (without ever have tested it) you just need to add a `$ref`. You can request them like this:
`o('http://my-odata.service.org').get('Product/$ref').query()`

I guess you can use post, put and delete here as well, to remove or add them. The details of this should be in the spec.

**Comment by GhostMayor** [comment]
if the index.d.ts file were used in the root directory and the entire project was done through it and is also specified in types (typings), as the TypeScript documentation says, it would be much easier to use your module for development
![image](https://user-images.githubusercontent.com/25086934/65543562-0d7dc200-df1a-11e9-8379-12422b5ce3cd.png)

**Comment by janhommes** [comment]
Agree, needs to be fixed. There are no typings attached :man_facepalming:

**Comment by janhommes** [comment]
Can you check the latest 1.0.3 release if the typings are now correct?

**Comment by GhostMayor** [comment]
Yes, I looked at the documentation that was generated, but I found a couple of comments.

in OHandler.d.ts
Look in line where use get method you write in correct,
having forgotten "')" and I also think that if you insert this example it will not work since " ' " will not be escaped, you need to use ' " ' to insert the text
![image](https://user-images.githubusercontent.com/25086934/65840287-de9f8b80-e31f-11e9-94f7-b8732c840fab.png)

OdataConfig
return "void" , but in defaultConfigValues returned "null"
![image](https://user-images.githubusercontent.com/25086934/65840334-7f8e4680-e320-11e9-9ccc-01e0bdb09184.png)
![image](https://user-images.githubusercontent.com/25086934/65840361-bbc1a700-e320-11e9-90d7-2682d838f3b2.png)

And
