### ISSUE TITLE
odata 1.0.3 missing Typescript module

### ISSUE THREAD

**Issue by haggholm** [janhommes/o.js#97]
```
node_modules/odata/dist/types/OdataConfig.d.ts:1:34 - error TS2307: Cannot find module './OdataBatchConfig'.

1 import { OdataBatchConfig } from "./OdataBatchConfig";
                                   ~~~~~~~~~~~~~~~~~~~~

node_modules/odata/dist/types/o.d.ts:28:15 - error TS2307: Cannot find module './OdataBatchConfig'.

28 export * from "./OdataBatchConfig";
                 ~~~~~~~~~~~~~~~~~~~~
```

**Comment by janhommes** [comment]
But it's there:
https://github.com/janhommes/o.js/blob/67cd681ea2bfc745052cc11ce951346d2eb1be64/src/o.ts#L80

You need to:
`import { OdataBatchConfig } from 'odata';`

**Comment by haggholm** [comment]
It is, indeed, in `o.js/src` (and `o.js/dist`), but it’s missing from `o.js/dist/types`, which is where another (sibling) module tries to import it from.

**Comment by janhommes** [comment]
arg, you are right. I have no idea why :face_with_head_bandage: 

I have added the interface to another file and published that. Can you check if the 1.0.4 is working now?

**Comment by haggholm** [comment]
Looks fine to me! :+1: I didn’t even notice; I’d set my dep version range to `"<=1.0.2 || ^1.0.4"` and all was well on reinstall this morning.

**Comment by janhommes** [comment]
Perfect, then I will close the issue. Thanks for reporting.
